---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    services:
    - name: wetherapp-fe
      image: nginx:1.23
      args:
      - --publish 80:80
      - --volume /etc/machine-id:/etc/machine-id:ro
    ansible_pull:
      enabled: true
      minutes_every: 60
      url: https://github.com/dshatohin/weatherapp.git
      playbook: ansible/frontend.yml
  roles:
  - systemd-docker
