---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    services:
    - name: weatherapp-frontend
      image: ghcr.io/dshatohin/weatherapp-frontend:latest
      args:
      - --publish 80:8000
    ansible_pull:
      enabled: true
      minutes_every: 30
      url: https://github.com/dshatohin/weatherapp.git
      playbook: ansible/frontend.yml
  roles:
  - systemd-docker
